/*
 * Parameter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"encoding/json"
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	openapi "parameters/go" //sw "github.com/GIT_USER_ID/GIT_REPO_ID/go"
	//
)

func main() {
	log.Printf("Server started")

	// router := openapi.NewRouter()

	// log.Fatal(router.Run(":8080"))
	data := map[string]any{"status": 200, "msg": "Done!"}

	if content, err := json.Marshal(data); err != nil {
		log.Fatal("MAIN %v", err.Error())

	} else {
		openapi.HandleCaching("./", "parameters.json", content)
	}

}
