openapi: '3.0.2'
info:
  title: Parameter
  version: '1.0'
servers:
  - url: https://api.flexcd.test/v1/


components:
  schemas:
    Parameter:
      type: object
      required:
        - "commandId"
        - "workflowId"
        - "id"
        - "name"
        - "default"
        - "description"
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string 
        default:
          type: string
        commandId:
          type: string
        workflowId: 
          type: string
    Response:
      type: string

paths:
  /parameter:
    post:
      operationId: AddParameter
      description: >- 
        Add a new paremeter for a specific command known as owner 
      summary: Add parameter
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Parameter"
      responses:
        '200':
          description: OK
    get:
      operationId: GetParameter
      description: >-
        Retrie a parameter by Id 
      parameters:
        - name: id 
          in: query
          required: true
          schema: 
            type: string 
      responses:
        '200':
          description: Parameter data
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response"
  /parameter/{workflowId}/{Id}:
    get: 
      operationId: GetParameterById
      description: >- 
        Retrieve the parameter by workflow Id and parameter Id
      parameters:
        - name: workflowId
          in: path
          required: true
          schema: 
            type: string
        - name: Id
          in: path 
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Parameter Value 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response"