/*
 * Parameter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Parameter struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description"`

	Default string `json:"default"`

	CommandId string `json:"commandId"`

	WorkflowId string `json:"workflowId"`
}
